import pygame

FINISHED=True
NOTFINISHED=False

WHEEL_DIAMETER=69
WHEEL_MAXRPS=1

ROBOTSIZE=20 # radius
PIXELRING_OUTERRADIUS=ROBOTSIZE
PIXELRING_LEDRADIUS=6
PIXELRING_NUMLEDS=8

STOPPED="STOPPED"
RUNNING="RUNNING"
DOWNLOADING="DOWNLOADING"
DRAGGING="DRAGGING"

PROGRAM_STOPPED=0
PROGRAM_PAUSED=1
PROGRAM_ACTIVE=2
PROGRAM_AWAITING_MOVE_COMPLETION=3
PROGRAM_AWAITING_DELAY_COMPLETION5=4
SYSTEM_CONFIGURATION_CONNECTION=5

# *IM<level> commands
# these should be ORed together to provide <level>
STATEMENT_CONFIRMATION=1
LINE_NUMBERS=2
ECHO_DOWNLOADS=4
DUMP_DOWNLOADS=8

CANVASCOLOR=0xEFEFEF
SONARCOLOR=0xEFEF00
NEARESTCOLOR=0x0000FF
INRANGECOLOR=0xFF0000
COLORS=["red","green","blue","cyan","magenta","yellow","white","black"]

LEFT="LEFT"
RIGHT="RIGHT"
UP="UP"
DOWN="DOWN"
UNDECIDED="UNDECIDED"




# wall collision distance
WALLMARGIN=50

# distance sensor
# used to return a value that is way too big
# to worry about
DISTANCESENSORRANGE=400
OUTOFRANGE=DISTANCESENSORRANGE+1000

# when reading lines of script indentation could be tabs or spaces
# we convert tabs to this
TABLENGTH=4

EOF="EOF"   # end of script